### ISSUE TITLE
Should it be able to handle .555 files ?

### ISSUE THREAD

**Issue by BazzaCuda** [bvschaik/citybuilding-tools#4]
Hi Bianca. I've downloaded SGReader from your Pandora's Box website. However, it doesn't open .555 files and the description on GitHub says it should. Was that something you planned to implement but haven't yet ? The executable is dated 02/01/2017 but the latest GitHub source code is from October 2017. Is there a build of the .exe later than 02/01/2017 somewhere please, and does it work with .555 files ?

Thanks.
Baz.

**Comment by bvschaik** [comment]
The 555 files cannot be opened without a SG file that references them: the 555 files only contain color pixels, an SG file is needed to interpret those colored pixels, so that's why you can only select SG2/SG3.
The last commit is from October 2017, but that was only the import of the SG reader source into Github.
