### ISSUE TITLE
What's the format of eng file?

### ISSUE THREAD

**Issue by lingjiameng** [bvschaik/citybuilding-tools#5]

**Comment by lingjiameng** [comment]
I want to make a Chinese translation for a game, but it's very confusing for me to decoding eng file.......
can you give me a more general explanation for the coding format? so I can use other tools like Python to implement a more general tools. Thanks.

**Comment by bvschaik** [comment]
Is [this wiki page](https://github.com/bvschaik/citybuilding-tools/wiki/ENG-file-format) enough for you to get started?
Do be aware that the games use images for each letter rather than a real font, and the images only contain characters in the Windows-CP1252 character encoding. Translation to Chinese will also need extra graphics and changes to the .exe file, and those are not easy to make.

**Comment by lingjiameng** [comment]
Thanks, it's very detailed.
